name: "Cpplint"

on:
  workflow_dispatch: null
  pull_request: null

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linting tools (cpplint)
        run: pipx run cpplint --recursive . --config=CPPLINT.cfg
